"""Application repository interface."""

from __future__ import annotations

import uuid
from collections.abc import Sequence
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from jobhunter.infrastructure.db.models import Application


class ApplicationRepository(Protocol):
    async def add(self, entity: Application) -> Application: ...
    async def get(self, id: uuid.UUID) -> Application | None: ...
    async def list(self, *, limit: int = 100, offset: int = 0) -> Sequence[Application]: ...
    async def update(self, entity: Application) -> Application: ...
    async def delete(self, id: uuid.UUID) -> None: ...
    async def get_by_job_profile(
        self, job_id: uuid.UUID, profile_id: uuid.UUID
    ) -> Application | None: ...
    async def list_by_status(self, status: str, *, limit: int = 100) -> Sequence[Application]: ...
    async def get_review_packet(self, application_id: uuid.UUID) -> Application | None: ...
