"""Company repository interface."""

from __future__ import annotations

import uuid
from collections.abc import Sequence
from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from jobhunter.infrastructure.db.models import Company


class CompanyRepository(Protocol):
    async def add(self, entity: Company) -> Company: ...
    async def get(self, id: uuid.UUID) -> Company | None: ...
    async def list(self, *, limit: int = 100, offset: int = 0) -> Sequence[Company]: ...
    async def update(self, entity: Company) -> Company: ...
    async def delete(self, id: uuid.UUID) -> None: ...
    async def get_by_name(self, name: str) -> Company | None: ...
    async def upsert_by_name(self, name: str, **fields: Any) -> Company: ...
