"""Job repository interface."""

from __future__ import annotations

import uuid
from collections.abc import Sequence
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from jobhunter.infrastructure.db.models import Job


class JobRepository(Protocol):
    async def add(self, entity: Job) -> Job: ...
    async def get(self, id: uuid.UUID) -> Job | None: ...
    async def list(self, *, limit: int = 100, offset: int = 0) -> Sequence[Job]: ...
    async def update(self, entity: Job) -> Job: ...
    async def delete(self, id: uuid.UUID) -> None: ...
    async def get_by_source_external(self, source: str, external_id: str) -> Job | None: ...
    async def exists_by_source_external(self, source: str, external_id: str) -> bool: ...
    async def list_unscored(self, profile_id: uuid.UUID, *, limit: int = 100) -> Sequence[Job]: ...
