"""UserProfile repository interface."""

from __future__ import annotations

import uuid
from collections.abc import Sequence
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from jobhunter.infrastructure.db.models import UserProfile


class UserProfileRepository(Protocol):
    async def add(self, entity: UserProfile) -> UserProfile: ...
    async def get(self, id: uuid.UUID) -> UserProfile | None: ...
    async def list(self, *, limit: int = 100, offset: int = 0) -> Sequence[UserProfile]: ...
    async def update(self, entity: UserProfile) -> UserProfile: ...
    async def delete(self, id: uuid.UUID) -> None: ...
    async def get_with_children(self, id: uuid.UUID) -> UserProfile | None: ...
    async def get_by_email(self, email: str) -> UserProfile | None: ...
