"""Queueing worker - creates Application rows (READY_FOR_REVIEW) for generated resume/cover pairs."""

import structlog
import uuid
from pathlib import Path
from sqlalchemy import select, text

logger = structlog.get_logger()


async def queue_applications_for_review():
    """Create Application rows (READY_FOR_REVIEW) for generated resume/cover pairs."""
    from jobhunter.infrastructure.db.unit_of_work import unit_of_work
    from jobhunter.infrastructure.db.models import (
        ResumeVersion,
        CoverLetterVersion,
        UserProfile,
        ApplicationAnswer,
        Screenshot,
    )

    async with unit_of_work() as session:
        result = await session.execute(select(ResumeVersion))
        resumes = result.scalars().all()
        logger.info("resumes_found", count=len(resumes))

        queued = 0
        for resume in resumes:
            cover_result = await session.execute(
                select(CoverLetterVersion)
                .where(CoverLetterVersion.job_id == resume.job_id)
                .where(CoverLetterVersion.profile_id == resume.profile_id)
                .limit(1)
            )
            cover = cover_result.scalar_one_or_none()
            if not cover:
                continue

            existing = await session.execute(
                text("SELECT 1 FROM applications WHERE job_id = :jid AND profile_id = :pid LIMIT 1"),
                {"jid": str(resume.job_id), "pid": str(resume.profile_id)},
            )
            if existing.first():
                continue

            profile = await session.get(UserProfile, resume.profile_id)
            app_id = uuid.uuid4()
            await session.execute(
                text("""
                    INSERT INTO applications (id, job_id, profile_id, resume_version_id,
                        cover_letter_version_id, status, notes)
                    VALUES (:id, :job_id, :profile_id, :rv_id, :clv_id, 'READY_FOR_REVIEW', :notes)
                """),
                {
                    "id": app_id,
                    "job_id": resume.job_id,
                    "profile_id": resume.profile_id,
                    "rv_id": resume.id,
                    "clv_id": cover.id,
                    "notes": "Auto-generated by M10 pipeline.",
                },
            )

            answers = [
                ApplicationAnswer(application_id=app_id, question="Full Name", value=profile.full_name, source="profile.full_name"),
                ApplicationAnswer(application_id=app_id, question="Email", value=profile.email, source="profile.email"),
            ]
            session.add_all(answers)

            key = f"screenshots/auto/{app_id}.png"
            minimal_png = (
                b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01"
                b"\x08\x02\x00\x00\x00\x90wS\xde\x00\x00\x00\x0cIDATx\x9cc\xf8\x0f"
                b"\x00\x00\x01\x01\x00\x05\x18\xd8N\x00\x00\x00\x00IEND\xaeB`\x82"
            )
            (Path("./storage") / key).parent.mkdir(parents=True, exist_ok=True)
            (Path("./storage") / key).write_bytes(minimal_png)
            session.add(Screenshot(application_id=app_id, step_label="auto_filled", storage_key=key, is_final=True))

            queued += 1
            logger.info("application_queued", app_id=str(app_id), job_id=str(resume.job_id))

        await session.flush()
        logger.info("queueing_complete", queued=queued)
        return {"queued": queued, "resumes_processed": len(resumes)}
